from . import auth_routes
from . import admin_routes
from . import user_routes
from . import prospect_routes
from . import assignment_routes
from . import call_log_routes
from . import spoc_report_routes
from . import spoc_visit_routes
from . import spoc_activity_routes
from . import spoc_escalation_routes
from . import followup_task_routes
from . import course_routes
from . import whatsapp_routes
from . import dashboard_routes
